packages = ["alacritty"]
shared_directories = ["alacritty_config"]
script = """
mkdir -p /home/${ALMA_USER}/.config/alacritty/
cp /shared_dirs/alacritty_config/alacritty.yml /home/${ALMA_USER}/.config/alacritty/alacritty.yml
chown ${ALMA_USER} /home/${ALMA_USER}/.config/alacritty/alacritty.yml
chown -R ${ALMA_USER} /home/${ALMA_USER}/.config/alacritty
chgrp -R ${ALMA_USER} /home/${ALMA_USER}/.config/alacritty
"""
environment_variables = ["ALMA_USER"]
