packages = ["neovim", "python-pynvim", "nodejs", "python2"]
aur_packages = ["pandoc-bin", "python2-pynvim"]
shared_directories = ["nvim_config", "nvim_base16"]

script = """
mkdir -p /home/${ALMA_USER}/.config/nvim
cp -r /shared_dirs/nvim_config/* /home/${ALMA_USER}/.config/nvim/
chown -R ${ALMA_USER} /home/${ALMA_USER}/.config/nvim
chgrp -R ${ALMA_USER} /home/${ALMA_USER}/.config/nvim
mkdir -p /home/${ALMA_USER}/.config/base16/vim/colors/
cp /shared_dirs/nvim_base16/base16-classic-dark.vim /home/${ALMA_USER}/.config/base16/vim/colors/
mkdir -p /home/${ALMA_USER}/.config/base16/shell/scripts/
cp /shared_dirs/nvim_base16/base16-classic-dark.sh /home/${ALMA_USER}/.config/base16/shell/scripts/
chown -R ${ALMA_USER} /home/${ALMA_USER}/.config/base16
chgrp -R ${ALMA_USER} /home/${ALMA_USER}/.config/base16

# Install plugins
sudo -u ${ALMA_USER} nvim --headless +PlugInstall +qall

# Update remote plugins to satisfy deoplete
sudo -u ${ALMA_USER} nvim --headless +UpdateRemotePlugins +qall

# Install scnvim
#sudo -u ${ALMA_USER} nvim --headless -c "call scnvim#install()" -c "qall"
mkdir -p /home/${ALMA_USER}/.local/share/SuperCollider/Extensions/scide_scnvim
chown -R ${ALMA_USER} /home/${ALMA_USER}/.local/share/SuperCollider
chown -R ${ALMA_USER} /home/${ALMA_USER}/.local/share/SuperCollider/Extensions/scide_scnvim
chgrp -R ${ALMA_USER} /home/${ALMA_USER}/.local/share/SuperCollider/Extensions/scide_scnvim

sudo -u ${ALMA_USER} ln -s /home/${ALMA_USER}/.vim/plugged/scnvim/scide_scnvim /home/${ALMA_USER}/.local/share/SuperCollider/Extensions/scide_scnvim/scnvim

# Install tidalvim
#cd /home/${ALMA_USER}/.vim/plugged/vim-tidal && sudo -u ${ALMA_USER} make install
sudo ln -s /home/${ALMA_USER}/.vim/plugged/vim-tidal/bin/tidal /usr/bin/tidal
sudo ln -s /home/${ALMA_USER}/.vim/plugged/vim-tidal/bin/tidalvim /usr/bin/tidalvim

"""

environment_variables = ["ALMA_USER"]
