packages = ["mpd", "ario"]
aur_packages = ["mpdris2"]
shared_directories = ["mpd_config"]
script = """
mkdir -p /home/${ALMA_USER}/.config/mpd/
cp /shared_dirs/mpd_config/mpd.conf /home/${ALMA_USER}/.config/mpd/mpd.conf
chown ${ALMA_USER} /home/${ALMA_USER}/.config/mpd/mpd.conf
chown -R ${ALMA_USER} /home/${ALMA_USER}/.config/mpd
chgrp -R ${ALMA_USER} /home/${ALMA_USER}/.config/mpd
mkdir -p /home/${ALMA_USER}/.config/systemd/user/default.target.wants/
ln -s /usr/lib/systemd/user/mpd.service /home/${ALMA_USER}/.config/systemd/user/default.target.wants/mpd.service
mkdir -p /home/${ALMA_USER}/.config/mpDris2
cp /shared_dirs/mpd_config/mpDris2.conf /home/${ALMA_USER}/.config/mpDris2/
chown ${ALMA_USER} /home/${ALMA_USER}/.config/mpDris2/mpDris2.conf
chown -R ${ALMA_USER} /home/${ALMA_USER}/.config/mpDris2
chgrp -R ${ALMA_USER} /home/${ALMA_USER}/.config/mpDris2
cp /shared_dirs/mpd_config/mpDris2.service /usr/lib/systemd/user/mpDris2.service
ln -s /usr/lib/systemd/user/mpDris2.service /home/${ALMA_USER}/.config/systemd/user/default.target.wants/mpDris2.service
"""
environment_variables = ["ALMA_USER"]
